services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: phishguard
      POSTGRES_USER: phishguard
      POSTGRES_PASSWORD: phishguard
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    command: celery -A app.tasks.celery_app:celery_app worker --loglevel=info -Q celery,emails,notifications

  beat:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    command: celery -A app.tasks.celery_app:celery_app beat --loglevel=info

  trainer:
    build:
      context: .
      dockerfile: docker/trainer.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    command: celery -A app.tasks.celery_app:celery_app worker --loglevel=info -Q trainer --concurrency=1 --pool=solo

volumes:
  postgres_data:
